# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('clue', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='landmark',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='clue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
