# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0002_auto_20171201_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='huntuser',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
