# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0004_huntuser_current_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='order_num',
            field=models.IntegerField(default=0),
        ),
    ]
