# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0007_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='game', max_length=255),
        ),
    ]
