# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0008_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_period',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='guess_penalty',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='game',
            name='guess_period',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='game',
            name='last_landmark_bonus',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='game',
            name='num_guesses',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='game',
            name='time_penalty',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='game',
            name='time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='huntuser',
            name='game_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='huntuser',
            name='guesses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='huntuser',
            name='penalties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='huntuser',
            name='question_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='huntuser',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='huntuser',
            name='time_requested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='landmark',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
