# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0009_auto_20171217_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_period',
            field=models.IntegerField(default=60),
        ),
    ]
